-----------------------------
-- VARIÁVEIS DE PARÂMETROS
-----------------------------
DECLARE @EMPRESA NUMERIC(15) = 98; -- insira aqui o numero da empresa
DECLARE @HOJE DATE = CAST(GETDATE() AS DATE);
DECLARE @SEIS_MESES_ATRAS DATE = DATEADD(MONTH, -6, @HOJE);

--------------------------------------------------
-- GERA TABELA TEMPORÁRIA DO CUSTO
--------------------------------------------------
;WITH PROD (PRODUTO, NF_RECENTE) AS (
    SELECT 
        PRODUTO, 
        MAX(NF_COMPRA)
    FROM ESPELHO
    WHERE EMPRESA = @EMPRESA
    GROUP BY PRODUTO
)
SELECT 
    E.NF_COMPRA_PRODUTO, 
    E.PRODUTO, 
    E.CUSTO AS CUSTO_UNITARIO,
    E.CUSTO_FINAL_LIQUIDO AS CUSTO_GERENCIAL
INTO #TEMP01
FROM ESPELHO E
JOIN PROD P ON P.PRODUTO = E.PRODUTO AND P.NF_RECENTE = E.NF_COMPRA
WHERE E.EMPRESA = @EMPRESA
ORDER BY E.PRODUTO;

--------------------------------------------------
-- GERA O RESULTADO DA CONSULTA
--------------------------------------------------
SELECT DISTINCT 
    A.PRODUTO,
    B.DESCRICAO,
    C.DESCRICAO AS SECAO,
    D.DESCRICAO AS GRUPO,
    I.DESCRICAO AS SUBGRUPO,
	T.DESCRICAO AS TIPO_DE_PRECO,
    A.ESTOQUE_SALDO AS ESTOQUE,
    F.PRECO_VENDA AS PRECO,
    G.CUSTO_UNITARIO,
    G.CUSTO_GERENCIAL,
    CAST(((F.PRECO_VENDA / G.CUSTO_UNITARIO) - 1) * 100 AS DECIMAL(10,3)) AS MARKUP_ATUAL_UNITARIO,
    CAST((100 - (G.CUSTO_UNITARIO / F.PRECO_VENDA) * 100) AS DECIMAL(10,3)) AS RENTABILIDADE_ATUAL_UNITARIO,
    CAST(((F.PRECO_VENDA / G.CUSTO_GERENCIAL) - 1) * 100 AS DECIMAL(10,3)) AS MARKUP_ATUAL_GERENCIAL,
    CAST((100 - (G.CUSTO_GERENCIAL / F.PRECO_VENDA) * 100) AS DECIMAL(10,3)) AS RENTABILIDADE_ATUAL_GERENCIAL,
    CASE 
        WHEN V.PRODUTO IS NOT NULL THEN 'SIM'
        ELSE 'NÃO'
    END AS TEVE_MOVIMENTO_6_MESES
FROM ESTOQUE_ATUAL AS A
JOIN PRODUTOS AS B ON B.PRODUTO = A.PRODUTO
JOIN SECOES_PRODUTOS AS C ON C.SECAO_PRODUTO = B.SECAO_PRODUTO
JOIN GRUPOS_PRODUTOS AS D ON D.GRUPO_PRODUTO = B.GRUPO_PRODUTO
JOIN PRODUTOS_VENDAS AS F ON F.PRODUTO = A.PRODUTO
JOIN TIPOS_PRECO AS T ON T.TIPO_PRECO = B.TIPO_PRECO
JOIN #TEMP01 AS G ON G.PRODUTO = A.PRODUTO
JOIN GRUPOS_PRECOS_EMPRESAS AS H ON H.GRUPO_PRECO = F.GRUPO_PRECO
JOIN SUBGRUPOS_PRODUTOS AS I ON I.SUBGRUPO_PRODUTO = B.SUBGRUPO_PRODUTO
LEFT JOIN (
    SELECT PRODUTO
    FROM VENDAS_AGRUPADAS
    WHERE EMPRESA = @EMPRESA
      AND MOVIMENTO BETWEEN @SEIS_MESES_ATRAS AND @HOJE
    GROUP BY PRODUTO
) AS V ON V.PRODUTO = A.PRODUTO
WHERE 
    A.CENTRO_ESTOQUE = @EMPRESA
    AND G.CUSTO_UNITARIO > 0 
    AND F.PRECO_VENDA > 0
    AND F.GRUPO_PRECO IN (
        SELECT TOP 1 GRUPO_PRECO 
        FROM GRUPOS_PRECOS_EMPRESAS 
        WHERE EMPRESA_USUARIA = @EMPRESA
    )
ORDER BY A.PRODUTO;