-----------------------------
-- VARIÁVEIS DE PARÂMETROS --
-----------------------------

DECLARE @EMPRESA NUMERIC(15) = 98 --insira aqui o numero da empresa;

--------------------------------------------------
-- GERA TABELA TEMPORÁRIA DO CUSTO --
--------------------------------------------------
;WITH PROD (PRODUTO, NF_RECENTE) AS (
    SELECT 
        PRODUTO, 
        MAX(NF_COMPRA)
    FROM ESPELHO
    WHERE EMPRESA = @EMPRESA
    GROUP BY PRODUTO
)
SELECT 
    E.NF_COMPRA_PRODUTO, 
    E.PRODUTO, 
    E.CUSTO AS CUSTO
INTO #TEMP01
FROM ESPELHO E
JOIN PROD ON PROD.PRODUTO = E.PRODUTO AND PROD.NF_RECENTE = E.NF_COMPRA
WHERE E.EMPRESA = @EMPRESA
ORDER BY E.PRODUTO

--------------------------------------------------
-- GERA O RESULTADO DA CONSULTA --
--------------------------------------------------
SELECT DISTINCT
    A.PRODUTO,
    B.DESCRICAO,
    C.DESCRICAO AS SECAO,
    D.DESCRICAO AS GRUPO,
    I.DESCRICAO AS SUBGRUPO,
	CL.DESCRICAO AS CLASSE,
    A.ESTOQUE_SALDO AS ESTOQUE,
    F.PRECO_VENDA AS PRECO,
    G.CUSTO AS CUSTO,
    J.ALIQUOTA_ICMS AS AL_ICMS,
    (F.PRECO_VENDA * (J.ALIQUOTA_ICMS / 100)) AS VALOR_ICMS,
    J.ALIQUOTA_PIS AS AL_PIS,
    (F.PRECO_VENDA * (J.ALIQUOTA_PIS / 100)) AS VALOR_PIS,
    J.ALIQUOTA_COFINS AS AL_COFINS,
    (F.PRECO_VENDA * (J.ALIQUOTA_COFINS / 100)) AS VALOR_COFINS,
    ISNULL(M.VALOR_BONIFICACAO, 0) AS VALOR_BONIFICACAO,
    
    (G.CUSTO
     + (F.PRECO_VENDA * (J.ALIQUOTA_ICMS / 100))
     + (F.PRECO_VENDA * (J.ALIQUOTA_PIS / 100))
     + (F.PRECO_VENDA * (J.ALIQUOTA_COFINS / 100))
     + ISNULL(M.VALOR_BONIFICACAO, 0)) AS CMV_GERAL,

    (((F.PRECO_VENDA / 
        (G.CUSTO
        + (F.PRECO_VENDA * (J.ALIQUOTA_ICMS / 100))
        + (F.PRECO_VENDA * (J.ALIQUOTA_PIS / 100))
        + (F.PRECO_VENDA * (J.ALIQUOTA_COFINS / 100))
        + ISNULL(M.VALOR_BONIFICACAO, 0))) - 1) * 100) AS MARKUP_ATUAL,

    (100 - (
        (G.CUSTO
        + (F.PRECO_VENDA * (J.ALIQUOTA_ICMS / 100))
        + (F.PRECO_VENDA * (J.ALIQUOTA_PIS / 100))
        + (F.PRECO_VENDA * (J.ALIQUOTA_COFINS / 100))
        + ISNULL(M.VALOR_BONIFICACAO, 0)) 
        / F.PRECO_VENDA) * 100) AS RENTABILIDADE_ATUAL

FROM ESTOQUE_ATUAL A

JOIN PRODUTOS B ON B.PRODUTO = A.PRODUTO
JOIN SECOES_PRODUTOS C ON C.SECAO_PRODUTO = B.SECAO_PRODUTO
JOIN GRUPOS_PRODUTOS D ON D.GRUPO_PRODUTO = B.GRUPO_PRODUTO
JOIN CLASSES_PRODUTOS CL ON CL.CLASSE_PRODUTO = B.CLASSE_PRODUTO
JOIN PRODUTOS_VENDAS F ON F.PRODUTO = A.PRODUTO
JOIN #TEMP01 G ON G.PRODUTO = A.PRODUTO
JOIN GRUPOS_PRECOS_EMPRESAS H ON H.GRUPO_PRECO = F.GRUPO_PRECO
JOIN SUBGRUPOS_PRODUTOS I ON I.SUBGRUPO_PRODUTO = B.SUBGRUPO_PRODUTO
JOIN GRUPOS_TRIBUTARIOS_PARAMETROS J ON J.GRUPO_TRIBUTARIO = B.GRUPO_TRIBUTARIO
JOIN ENDERECOS K ON K.ENTIDADE = A.CENTRO_ESTOQUE
LEFT JOIN BONIFICACOES L 
    ON L.GRUPO_PRECO = F.GRUPO_PRECO 
    AND L.DATA_FIM >= GETDATE()

LEFT JOIN BONIFICACOES_PRODUTOS M 
    ON M.BONIFICACAO = L.BONIFICACAO 
    AND M.PRODUTO = A.PRODUTO

WHERE 
    A.CENTRO_ESTOQUE = @EMPRESA
    AND G.CUSTO > 0
    AND F.PRECO_VENDA > 0
    AND F.GRUPO_PRECO IN (
        SELECT TOP 1 GRUPO_PRECO 
        FROM GRUPOS_PRECOS_EMPRESAS 
        WHERE EMPRESA_USUARIA = @EMPRESA
    )
    AND J.OPERACAO_FISCAL = 28
    AND (J.ESTADO_ORIGEM = K.ESTADO AND J.ESTADO_DESTINO = K.ESTADO)

ORDER BY A.PRODUTO