SELECT
	EU.EMPRESA_USUARIA,
	EU.NOME,
	SUM(A.QUANTIDADE) AS QTDE_TOTAL_COMPRA,
    SUM(A.VALOR_PRODUTO_LIQUIDO * A.QUANTIDADE) AS VALOR_TOTAL_COMPRA

FROM
    ESPELHO A WITH(NOLOCK)
JOIN
    PRODUTOS B WITH(NOLOCK) ON B.PRODUTO = A.PRODUTO
JOIN 
	EMPRESAS_USUARIAS EU ON A.EMPRESA = EU.EMPRESA_USUARIA
WHERE
	--A.EMPRESA IN ()AND
	--A.MOVIMENTO BETWEEN @MOVIMENTO_INI AND @MOVIMENTO_FIM AND
    A.OPERACAO_FISCAL = 1 
GROUP BY
	EU.EMPRESA_USUARIA,
	EU.NOME
ORDER BY
    EU.EMPRESA_USUARIA;