-----------------------------
-- VARIÁVEIS DE PARÂMETROS --
-----------------------------
DECLARE @MOVIMENTO_INICIAL DATE        = '20250729'
DECLARE @MOVIMENTO_FINAL   DATE        = '20250730'
DECLARE @EMPRESA           NUMERIC(15) = 109

--------------------------------------------------
-- GERA TABELA TEMPORÁRIA --
--------------------------------------------------
SELECT
	C.GRUPO_PRODUTO									AS GRUPO_PRODUTO,
	D.DESCRICAO										AS DESCRICAO,
    SUM(A.VENDA_BRUTA)								AS VENDA_BRUTA,
    SUM(A.DESCONTO)									AS DESCONTO,
    SUM(A.DESCONTO_AUTOMATICO)						AS DESCONTO_AUTOMATICO,
    SUM(A.DESCONTO) - SUM(A.DESCONTO_AUTOMATICO)	AS DESCONTO_CONCEDIDO,
    SUM(A.VENDA_LIQUIDA)							AS VENDA_LIQUIDA,
    SUM(A.IMPOSTOS)									AS IMPOSTOS,
    SUM(A.QUANTIDADE * ISNULL(B.CUSTO_CONTABIL, 0))	AS CMV,
    SUM(A.VENDA_LIQUIDA) - SUM(A.IMPOSTOS) - SUM(A.QUANTIDADE * ISNULL(B.CUSTO_CONTABIL, 0)) AS LUCRO_BRUTO
INTO #TEMP_01
FROM VENDAS_ANALITICAS A WITH(NOLOCK)
    JOIN EMPRESAS_USUARIAS X WITH(NOLOCK) ON X.EMPRESA_USUARIA = A.EMPRESA
    LEFT JOIN CUSTO_MEDIO_MENSAL_EMPRESA_CONTABIL B WITH(NOLOCK) ON B.PRODUTO = A.PRODUTO
		AND B.EMPRESA_CONTABIL = X.EMPRESA_CONTABIL
		AND B.MES = MONTH(A.MOVIMENTO)
		AND B.ANO = YEAR(A.MOVIMENTO)
    LEFT JOIN PRODUTOS C WITH(NOLOCK) ON C.PRODUTO = A.PRODUTO
    LEFT JOIN GRUPOS_PRODUTOS D WITH(NOLOCK) ON D.GRUPO_PRODUTO = C.GRUPO_PRODUTO
WHERE A.MOVIMENTO BETWEEN @MOVIMENTO_INICIAL AND @MOVIMENTO_FINAL
    AND (A.EMPRESA = @EMPRESA)
GROUP BY C.GRUPO_PRODUTO, D.DESCRICAO

--------------------------------------------------
-- GERA O RESULTADO DA CONSULTA --
--------------------------------------------------
SELECT

    DESCRICAO											AS DESCRICAO,
    VENDA_BRUTA											AS VENDA_BRUTA,
    DESCONTO_AUTOMATICO									AS DESCONTO_AUTOMATICO,
    DESCONTO_CONCEDIDO									AS DESCONTO_CONCEDIDO,
    VENDA_LIQUIDA										AS VENDA_LIQUIDA,
    CMV													AS CMV,
    (VENDA_LIQUIDA - (CMV + IMPOSTOS))		AS LUCRO_BRUTO,
    CASE
        WHEN VENDA_LIQUIDA > 0 THEN 100 - ((CMV + IMPOSTOS) / VENDA_LIQUIDA) * 100
        ELSE 0
    END													AS PLUCRO_BRUTO
FROM #TEMP_01
ORDER BY GRUPO_PRODUTO